# Site settings
title: Jekyll for Web Designers
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
baseurl: "/jekyll_sandbox"
url: "https://smerth.github.io/jekyll_sandbox/"
tagline: A basic guide to Jekyll

# Require gems
# may not be necessary as require plugins is definitely used by the app...
gems: [jekyll-paginate, jekyll-gist]

# Require plugins
plugins: [jekyll-paginate, jekyll-gist]

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
paginate: 4
paginate_path: "/blog/page:num/"
permalink: /blog/:title
