# Site settings
title: Jekyll for Web Designers
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
domain: smerth.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://smerth.github.io/jekyll-sandbox # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /jekyll-sandbox # place folder name if the site is served in a subfolder

tagline: A basic guide to Jekyll

# Require plugins
plugins: [jekyll-paginate, jekyll-gist]

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
paginate: 4
paginate_path: "/blog/page:num/"
permalink: /blog/:title
